export const QUIZ_START = 'QUIZ_START'
export const QUESTION_ADD = 'QUESTION_ADD'
export const QUESTION_ANSWERED_CORRECT = 'QUESTION_ANSWERED_CORRECT'
export const QUESTION_ANSWERED_INCORRECT = 'QUESTION_ANSWERED_INCORRECT'

export DECK_CREATE = 'DECK_CREATE'
